"""
report_builder.py
─────────────────
Builds a plain-text analysis report from the full analysis result.
No external PDF library. Produces structured text that the frontend
can trigger as a .txt download.

The report includes:
  Header: ASTra Analysis Report, timestamp, language
  Section 1: Complexity — time, space, confidence
  Section 2: Cyclomatic Complexity — score, risk, per-function table
  Section 3: Halstead Metrics — all 8 metrics with labels
  Section 4: Data Flow Findings — each finding with severity
  Section 5: Anti-Patterns — each finding with severity
  Section 6: Dead Code — each finding with severity
  Section 7: Type Inference — variable→type table
  Section 8: Eco Score — rating, carbon, energy
  Section 9: Suggestions — bulleted list
  Footer: "Generated by ASTra — AST-Native Code Intelligence"

Format it with ASCII box drawing:
  ╔══════════════════════════════════════╗
  ║  ASTra Analysis Report               ║
  ╚══════════════════════════════════════╝

  ┌─ COMPLEXITY ──────────────────────────┐
  │ Time:  O(n²)   Confidence: 91%        │
  │ Space: O(n)    Confidence: 85%        │
  └───────────────────────────────────────┘

Returns the report as a plain string.
"""

from datetime import datetime, timezone


class ReportBuilder:
    def __init__(self, analysis_result: dict, code: str) -> None:
        self.result = analysis_result
        self.code = code
        self.width = 52  # inner content width (between │ borders)

    def build(self) -> str:
        """Build and return the full report string."""
        sections = [
            self._header(),
            self._section_complexity(),
            self._section_cyclomatic(),
            self._section_halstead(),
            self._section_data_flow(),
            self._section_anti_patterns(),
            self._section_dead_code(),
            self._section_type_info(),
            self._section_eco(),
            self._section_suggestions(),
            self._footer(),
        ]
        return "\n".join(s for s in sections if s)

    # ─────────────────────────────────────────────────────────────────────────
    # Helpers
    # ─────────────────────────────────────────────────────────────────────────

    def _pad(self, text: str, width: int) -> str:
        """Left-pad text to width, truncating if needed."""
        return text[:width].ljust(width)

    def _box(self, title: str, lines: list[str]) -> str:
        """Render a  ┌─ TITLE ──┐ ... └──┘  section."""
        w = self.width
        # Title part: ─ TITLE ─────
        title_str = f" {title} "
        dashes_right = "─" * max(0, w - len(title_str) - 1)
        top = f"┌─{title_str}{dashes_right}┐"
        bottom = "└" + "─" * (w + 2) + "┘"

        body_lines = []
        for line in lines:
            padded = self._pad(line, w)
            body_lines.append(f"│ {padded} │")

        return "\n".join([top] + body_lines + [bottom])

    def _header(self) -> str:
        """Render the ╔══╗ header with timestamp."""
        w = self.width
        inner = w + 2  # total inner space between ║ borders
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        language = self.result.get("language", "python").capitalize()

        top    = "╔" + "═" * inner + "╗"
        blank  = "║" + " " * inner + "║"
        title_text = "  ASTra Analysis Report"
        title  = "║" + self._pad(title_text, inner) + "║"
        ts_text = f"  {timestamp}  ·  {language}"
        ts     = "║" + self._pad(ts_text, inner) + "║"
        bottom = "╚" + "═" * inner + "╝"

        return "\n".join([top, title, ts, blank, bottom])

    def _section_complexity(self) -> str:
        analysis = self.result.get("analysis", {})
        time_c   = analysis.get("time_complexity", "N/A")
        space_c  = analysis.get("space_complexity", "N/A")
        conf     = analysis.get("confidence") or {}
        time_conf  = conf.get("time_confidence")
        space_conf = conf.get("space_confidence")

        lines = [
            f"Time:   {time_c:<12}" + (f"  Confidence: {time_conf*100:.0f}%" if time_conf is not None else ""),
            f"Space:  {space_c:<12}" + (f"  Confidence: {space_conf*100:.0f}%" if space_conf is not None else ""),
        ]

        alt = conf.get("time_alternative")
        if alt:
            lines.append(f"Alt:    {alt}  ({conf.get('time_alt_reason', '')})")

        reductions = conf.get("time_reductions", [])
        for r in reductions[:3]:
            lines.append(f"  ↓ {r}")

        return "\n" + self._box("COMPLEXITY", lines)

    def _section_cyclomatic(self) -> str:
        cyc = self.result.get("analysis", {}).get("cyclomatic")
        if not cyc:
            return ""

        score = cyc.get("score", "N/A")
        risk  = cyc.get("risk_label", cyc.get("risk_level", "N/A"))
        lines = [
            f"Score:  {score}",
            f"Risk:   {risk}",
        ]

        per_fn = cyc.get("per_function", [])
        if per_fn:
            lines.append("")
            lines.append(f"{'Function':<22} {'Score':>6}  Risk")
            lines.append("─" * 40)
            for fn in per_fn[:10]:
                name = str(fn.get("name", "?"))[:21]
                lines.append(f"{name:<22} {fn.get('score', '?'):>6}  {fn.get('risk_level', '?')}")

        return "\n" + self._box("CYCLOMATIC COMPLEXITY", lines)

    def _section_halstead(self) -> str:
        hal = self.result.get("analysis", {}).get("halstead")
        if not hal:
            return ""

        metrics = [
            ("Distinct Operators (η₁)", "distinct_operators"),
            ("Distinct Operands  (η₂)", "distinct_operands"),
            ("Total Operators    (N₁)", "total_operators"),
            ("Total Operands     (N₂)", "total_operands"),
            ("Vocabulary         (η)",  "vocabulary"),
            ("Length             (N)",  "length"),
            ("Volume             (V)",  "volume"),
            ("Difficulty         (D)",  "difficulty"),
            ("Effort             (E)",  "effort"),
            ("Bugs Estimated     (B)",  "bugs_estimated"),
        ]
        lines = []
        for label, key in metrics:
            val = hal.get(key)
            if val is None:
                continue
            if isinstance(val, float):
                val_str = f"{val:.3f}"
            else:
                val_str = str(val)
            lines.append(f"{label:<28}  {val_str}")

        if not lines:
            return ""

        return "\n" + self._box("HALSTEAD METRICS", lines)

    def _section_data_flow(self) -> str:
        findings = self.result.get("data_flow", [])
        if not findings:
            return ""

        lines = [f"{len(findings)} finding(s) detected", ""]
        for f in findings[:15]:
            sev  = str(f.get("severity", "")).upper()
            msg  = str(f.get("message", f.get("pattern", "")))[:42]
            line_no = f.get("line")
            loc  = f"  line {line_no}" if line_no else ""
            lines.append(f"[{sev:<8}] {msg}{loc}")

        return "\n" + self._box("DATA FLOW FINDINGS", lines)

    def _section_anti_patterns(self) -> str:
        patterns = self.result.get("anti_patterns", [])
        if not patterns:
            return ""

        lines = [f"{len(patterns)} issue(s) found", ""]
        for p in patterns[:15]:
            sev  = str(p.get("severity", "")).upper()
            name = str(p.get("pattern", p.get("type", "?"))).replace("_", " ")[:32]
            msg  = str(p.get("message", ""))[:40]
            lines.append(f"[{sev:<8}] {name}")
            if msg:
                lines.append(f"           {msg}")

        return "\n" + self._box("ANTI-PATTERNS", lines)

    def _section_dead_code(self) -> str:
        dead = self.result.get("analysis", {}).get("dead_code", [])
        if not dead:
            return ""

        lines = [f"{len(dead)} issue(s) found", ""]
        for d in dead[:15]:
            sev  = str(d.get("severity", "")).upper()
            pat  = str(d.get("pattern", "")).replace("_", " ")[:28]
            name = d.get("name", "")
            msg  = str(d.get("message", ""))[:40]
            suffix = f" '{name}'" if name else ""
            lines.append(f"[{sev:<8}] {pat}{suffix}")
            if msg:
                lines.append(f"           {msg}")

        return "\n" + self._box("DEAD CODE", lines)

    def _section_type_info(self) -> str:
        ti = self.result.get("analysis", {}).get("type_info")
        if not ti:
            return ""

        variables = ti.get("variables", {})
        param_hints = ti.get("parameter_hints", {})

        if not variables and not param_hints:
            return ""

        lines = []
        if variables:
            lines.append(f"{'Variable':<18} {'Type':<14} Confidence")
            lines.append("─" * 44)
            for var, info in list(variables.items())[:15]:
                typ  = str(info.get("type", "?"))[:13]
                conf = info.get("confidence", 0)
                lines.append(f"{var:<18} {typ:<14} {conf*100:.0f}%")

        if param_hints:
            lines.append("")
            lines.append("Parameter hints (inferred from usage):")
            for param, typ in list(param_hints.items())[:8]:
                lines.append(f"  {param}: {typ}")

        return "\n" + self._box("TYPE INFERENCE", lines)

    def _section_eco(self) -> str:
        eco = self.result.get("analysis", {}).get("eco_metrics")
        if not eco:
            return ""

        rating  = eco.get("eco_rating", "N/A")
        score   = eco.get("eco_score_100", "N/A")
        carbon  = eco.get("carbon_gco2e_1m", "N/A")
        energy  = eco.get("energy_joules_1m", "N/A")

        lines = [
            f"Rating:   {rating} ({score}/100)",
            f"Carbon:   {carbon} gCO₂e per 1M executions",
            f"Energy:   {energy} Joules per 1M executions",
        ]

        return "\n" + self._box("ECO SCORE", lines)

    def _section_suggestions(self) -> str:
        suggestions = self.result.get("suggestions", [])
        if not suggestions:
            return ""

        lines = []
        for s in suggestions[:12]:
            text = str(s)[:48]
            lines.append(f"• {text}")

        return "\n" + self._box("SUGGESTIONS", lines)

    def _footer(self) -> str:
        w = self.width
        inner = w + 2
        text = "Generated by ASTra — AST-Native Code Intelligence"
        padded = text[:inner].center(inner)
        return "\n" + "─" * (inner + 2) + "\n" + padded + "\n" + "─" * (inner + 2)
